
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package scanner;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMBER = 13;
  public static final int TRUE = 11;
  public static final int STRING = 14;
  public static final int EOF = 0;
  public static final int FALSE = 12;
  public static final int QUASIQUOTE = 7;
  public static final int RBRACKET = 5;
  public static final int DOT = 10;
  public static final int UNQUOTE_SPLICING = 9;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int QUOTE = 6;
  public static final int IDENTIFIER = 15;
  public static final int UNQUOTE = 8;
  public static final int LBRACKET = 4;
  public static final int LPAREN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "QUOTE",
  "QUASIQUOTE",
  "UNQUOTE",
  "UNQUOTE_SPLICING",
  "DOT",
  "TRUE",
  "FALSE",
  "NUMBER",
  "STRING",
  "IDENTIFIER"
  };
}

