// ----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
// ----------------------------------------------------

package scanner;

/** CUP generated interface containing symbol constants. */
public interface sym {
    /* terminals */
    public static final int KW_DEFINE = 8;
    public static final int KW_LETREC = 20;
    public static final int KW_IF = 9;
    public static final int RPAREN = 3;
    public static final int CHARACTER = 25;
    public static final int KW_DO = 21;
    public static final int IDENTIFIER = 23;
    public static final int VECTOR_START = 6;
    public static final int KW_LETSTAR = 19;
    public static final int LPAREN = 2;
    public static final int KW_LAMBDA = 11;
    public static final int QUOTE = 5;
    public static final int KW_SET = 10;
    public static final int BOOLEAN = 27;
    public static final int STRING = 24;
    public static final int KW_CASE = 15;
    public static final int NUMBER = 26;
    public static final int EOF = 0;
    public static final int KW_LET = 18;
    public static final int KW_COND = 13;
    public static final int error = 1;
    public static final int DOT = 4;
    public static final int ARROW = 7;
    public static final int KW_BEGIN = 12;
    public static final int KW_DELAY = 22;
    public static final int KW_AND = 16;
    public static final int KW_OR = 17;
    public static final int KW_ELSE = 14;
    public static final String[] terminalNames =
            new String[] {
                "EOF",
                "error",
                "LPAREN",
                "RPAREN",
                "DOT",
                "QUOTE",
                "VECTOR_START",
                "ARROW",
                "KW_DEFINE",
                "KW_IF",
                "KW_SET",
                "KW_LAMBDA",
                "KW_BEGIN",
                "KW_COND",
                "KW_ELSE",
                "KW_CASE",
                "KW_AND",
                "KW_OR",
                "KW_LET",
                "KW_LETSTAR",
                "KW_LETREC",
                "KW_DO",
                "KW_DELAY",
                "IDENTIFIER",
                "STRING",
                "CHARACTER",
                "NUMBER",
                "BOOLEAN"
            };
}
